import { prisma } from '../../../../../services/prisma.js';
import { telegramOutbox } from '../../messaging/outbox/telegramOutbox.js';
import { ActionTokens, buildCallbackData } from '../../core/utils/callbackUtils.js';
import type { PipelineContext } from '../../core/types.js';
import { normalizeBotConfigChatId } from '../../core/utils/telegramChatId.js';
import { publicIdService } from '../../../../../services/publicId.service.js';

export type TestScenarioCode =
  | 'lead_buy'
  | 'lead_sell'
  | 'support'
  | 'b2b_reg_new'
  | 'b2b_reg_agent'
  | 'b2b_request'
  | 'b2b_sell_form'
  | 'b2b_sell_inv'
  | 'b2b_fit';

export type TestScenarioActor = {
  tgUserId: string;
  username?: string | null;
  displayName: string;
};

type TestPanelItem = {
  code: TestScenarioCode;
  label: string;
};

export type TestPanelDefinition = {
  title: string;
  items: TestPanelItem[];
};

const LEAD_PANEL: TestPanelDefinition = {
  title: '🧪 Тестові сценарії Lead',
  items: [
    { code: 'lead_buy', label: '🟢 LEAD BUY' },
    { code: 'lead_sell', label: '🟣 LEAD SELL (з діями)' },
    { code: 'support', label: '🆘 SUPPORT' }
  ]
};

const B2B_PANEL: TestPanelDefinition = {
  title: '🧪 Тестові сценарії B2B',
  items: [
    { code: 'b2b_reg_new', label: '🟡 B2B REG NEW (з approve/reject)' },
    { code: 'b2b_reg_agent', label: '👤 B2B REG AGENT' },
    { code: 'b2b_request', label: '🔵 B2B REQUEST' },
    { code: 'b2b_sell_form', label: '🟣 B2B SELL FORM' },
    { code: 'b2b_sell_inv', label: '🚙 B2B SELL INVENTORY' },
    { code: 'b2b_fit', label: '🔥 FIT' }
  ]
};

const toText = (value: unknown) => String(value || '').trim();

const nowIso = () => new Date().toISOString();

const randomSuffix = () => Math.random().toString(36).slice(2, 8);

const resolveCompanyId = (ctx: PipelineContext) => {
  const companyId = toText(ctx.companyId || ctx.bot?.companyId);
  if (!companyId) throw new Error('missing_company_id');
  return companyId;
};

const resolveAdminChatId = (ctx: PipelineContext) => {
  return toText(normalizeBotConfigChatId(ctx.bot?.adminChatId));
};

const sendAdmin = async (ctx: PipelineContext, text: string, replyMarkup?: any) => {
  if (!ctx.bot) return false;
  const adminChatId = resolveAdminChatId(ctx);
  if (!adminChatId) return false;
  await telegramOutbox.sendMessage({
    botId: ctx.bot.id,
    token: ctx.bot.token,
    chatId: adminChatId,
    text,
    replyMarkup,
    companyId: ctx.companyId || ctx.bot.companyId
  });
  return true;
};

const randomInviteCode = () => {
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let code = 'CDL-';
  for (let i = 0; i < 6; i += 1) {
    code += alphabet[Math.floor(Math.random() * alphabet.length)] || 'X';
  }
  return code;
};

const ensureUniqueInviteCode = async () => {
  for (let i = 0; i < 120; i += 1) {
    const code = randomInviteCode();
    const exists = await prisma.partnerCompany.findUnique({
      where: { inviteCode: code },
      select: { id: true }
    });
    if (!exists) return code;
  }
  return `CDL-${Date.now().toString(36).slice(-6).toUpperCase()}`;
};

const ensureTestPartner = async (ctx: PipelineContext) => {
  const companyId = resolveCompanyId(ctx);
  const existing = await prisma.partnerCompany.findFirst({
    where: {
      companyId,
      name: 'TEST PARTNER'
    }
  });
  if (existing) return existing;

  const inviteCode = await ensureUniqueInviteCode();
  const partnerCode = inviteCode.replace(/^CDL-/, 'P-');
  return prisma.partnerCompany.create({
    data: {
      companyId,
      name: 'TEST PARTNER',
      city: 'Львів',
      contact: '+380670000000',
      notes: 'Auto-generated by admin test panel',
      inviteCode,
      partnerCode
    }
  });
};

const createLeadBuyScenario = async (ctx: PipelineContext, actor: TestScenarioActor) => {
  if (!ctx.bot) throw new Error('missing_bot');
  const companyId = resolveCompanyId(ctx);
  const lead = await prisma.lead.create({
    data: {
      companyId,
      botId: ctx.bot.id,
      source: 'TELEGRAM_TEST',
      status: 'NEW',
      userTgId: actor.tgUserId,
      clientName: actor.displayName || 'Тестовий користувач',
      phone: '+380671112233',
      request: 'Підбір BMW X5',
      payload: {
        test: true,
        testScenario: 'lead_buy',
        createdByAdminTgId: actor.tgUserId,
        language: 'UK',
        filters: {
          brand: 'BMW',
          model: 'X5',
          yearMin: 2019,
          budgetMax: 35000,
          mileageMax: 120000,
          city: 'Львів'
        }
      } as any
    }
  });

  await sendAdmin(ctx, [
    '🧪 [TEST] 🟢 [LEAD BUY]',
    `Lead ID: ${lead.id}`,
    `👤 ${actor.displayName}`,
    `username: ${actor.username ? `@${actor.username}` : '—'}`,
    `tgUserId: ${actor.tgUserId}`,
    '🚗 Запит: BMW X5',
    '💰 Бюджет: до 35000 USD',
    '📞 Контакт: +380671112233',
    `🕒 ${nowIso()}`
  ].join('\n'));
};

const createLeadSellScenario = async (ctx: PipelineContext, actor: TestScenarioActor) => {
  if (!ctx.bot) throw new Error('missing_bot');
  const companyId = resolveCompanyId(ctx);
  const sellDraft = {
    brand: 'Audi',
    model: 'Q7',
    year: 2020,
    mileage: 118000,
    fuel: 'Дизель',
    transmission: 'Автомат',
    drive: 'Повний',
    condition: 'Добрий',
    description: 'Тестова заявка: без реальних контактів',
    price: 33000,
    city: 'Львів',
    phone: '+380671234567',
    photos: []
  };

  const lead = await prisma.lead.create({
    data: {
      companyId,
      botId: ctx.bot.id,
      source: 'TELEGRAM_TEST',
      status: 'NEW',
      userTgId: actor.tgUserId,
      clientName: actor.displayName || 'Тестовий продавець',
      phone: sellDraft.phone,
      request: `${sellDraft.brand} ${sellDraft.model} ${sellDraft.year}`,
      payload: {
        test: true,
        testScenario: 'lead_sell',
        createdByAdminTgId: actor.tgUserId,
        leadType: 'SELL',
        sellDraft,
        sellAdminState: {}
      } as any
    }
  });

  const adminMarkup = {
    inline_keyboard: [
      [{ text: '💾 Зберегти в інвентар', callback_data: buildCallbackData(ActionTokens.LS_SAVE, lead.id) }],
      [{ text: '📣 Опублікувати в CarTié', callback_data: buildCallbackData(ActionTokens.LS_PUB_CARTIE, lead.id) }],
      [{ text: '🤝 Опублікувати в B2B', callback_data: buildCallbackData(ActionTokens.LS_PUB_B2B, lead.id) }],
      [{ text: '📝 Створити B2B запит', callback_data: buildCallbackData(ActionTokens.LS_REQ_B2B, lead.id) }]
    ]
  };

  await sendAdmin(ctx, [
    '🧪 [TEST] 🟣 [LEAD SELL]',
    `Lead ID: ${lead.id}`,
    `👤 ${actor.displayName}`,
    `username: ${actor.username ? `@${actor.username}` : '—'}`,
    `tgUserId: ${actor.tgUserId}`,
    `Авто: ${sellDraft.brand} ${sellDraft.model} ${sellDraft.year}`,
    `Ціна: ${sellDraft.price} USD`,
    `Пробіг: ${sellDraft.mileage} км`,
    `Контакт: ${sellDraft.phone}`,
    `🕒 ${nowIso()}`
  ].join('\n'), adminMarkup);
};

const createSupportScenario = async (ctx: PipelineContext, actor: TestScenarioActor) => {
  if (!ctx.bot) throw new Error('missing_bot');
  const companyId = resolveCompanyId(ctx);
  const text = 'Тестове звернення до підтримки: перевірка маршруту в адмін-чат.';
  const contact = '+380631112233';
  const item = {
    text,
    contact,
    date: nowIso(),
    from: 'user',
    test: true
  };

  const existing = await prisma.supportTicket.findFirst({
    where: {
      botId: ctx.bot.id,
      tgUserId: actor.tgUserId,
      status: 'OPEN'
    },
    orderBy: { createdAt: 'desc' }
  });

  if (existing) {
    const thread = Array.isArray(existing.thread) ? [...existing.thread] : [];
    thread.push(item as any);
    await prisma.supportTicket.update({
      where: { id: existing.id },
      data: {
        text,
        context: {
          ...(typeof existing.context === 'object' && existing.context ? (existing.context as any) : {}),
          contact,
          test: true,
          testScenario: 'support',
          createdByAdminTgId: actor.tgUserId
        } as any,
        thread: thread as any
      }
    });
  } else {
    await prisma.supportTicket.create({
      data: {
        companyId,
        botId: ctx.bot.id,
        tgUserId: actor.tgUserId,
        chatId: toText(ctx.chatId),
        text,
        context: {
          contact,
          test: true,
          testScenario: 'support',
          createdByAdminTgId: actor.tgUserId
        } as any,
        thread: [item] as any,
        status: 'OPEN'
      }
    });
  }

  await sendAdmin(ctx, [
    '🧪 [TEST] 🆘 [SUPPORT]',
    `👤 ${actor.displayName}`,
    `username: ${actor.username ? `@${actor.username}` : '—'}`,
    `tgUserId: ${actor.tgUserId}`,
    `📞 Контакт: ${contact}`,
    '',
    text
  ].join('\n'));
};

const createB2BRegNewScenario = async (ctx: PipelineContext, actor: TestScenarioActor) => {
  if (!ctx.bot) throw new Error('missing_bot');
  const companyId = resolveCompanyId(ctx);
  const payload = {
    kind: 'NEW_PARTNER',
    chatId: toText(ctx.chatId) || null,
    company: {
      name: 'TEST PARTNER',
      city: 'Львів',
      phone: '+380671112244',
      note: 'Створено через admin test panel'
    },
    applicant: {
      tgUserId: actor.tgUserId,
      username: actor.username || null,
      firstName: actor.displayName || 'Test',
      lastName: 'Admin',
      contact: '+380671112244'
    },
    test: true,
    testScenario: 'b2b_reg_new',
    createdByAdminTgId: actor.tgUserId
  };

  const accessRequest = await prisma.b2bAccessRequest.create({
    data: {
      companyId,
      botId: ctx.bot.id,
      tgUserId: actor.tgUserId,
      username: actor.username || null,
      fullName: actor.displayName || 'Test Admin',
      payload: payload as any,
      reason: JSON.stringify(payload),
      status: 'NEW'
    }
  });

  await sendAdmin(ctx, [
    '🧪 [TEST] 🟡 [B2B REG]',
    'Заявка на реєстрацію партнера',
    `ID заявки: ${accessRequest.id}`,
    `👤 ${actor.displayName}`,
    `username: ${actor.username ? `@${actor.username}` : '—'}`,
    `tgUserId: ${actor.tgUserId}`,
    'Компанія: TEST PARTNER',
    'Контакт: +380671112244'
  ].join('\n'), {
    inline_keyboard: [[
      { text: '✅ Підтвердити', callback_data: buildCallbackData(ActionTokens.BR_APPROVE, accessRequest.id) },
      { text: '❌ Відхилити', callback_data: buildCallbackData(ActionTokens.BR_REJECT, accessRequest.id) }
    ]]
  });
};

const createB2BRegAgentScenario = async (ctx: PipelineContext, actor: TestScenarioActor) => {
  const companyId = resolveCompanyId(ctx);
  const partner = await ensureTestPartner(ctx);
  const existing = await prisma.partnerUser.findFirst({
    where: { telegramId: actor.tgUserId }
  });

  if (existing) {
    await prisma.partnerUser.update({
      where: { id: existing.id },
      data: {
        companyId,
        partnerId: partner.id,
        role: 'AGENT',
        phone: existing.phone || '+380671110000'
      }
    });
  } else {
    await prisma.partnerUser.create({
      data: {
        name: actor.displayName || 'Test Agent',
        lastName: null,
        telegramId: actor.tgUserId,
        phone: '+380671110000',
        role: 'AGENT',
        partnerId: partner.id,
        companyId
      }
    });
  }

  await sendAdmin(ctx, [
    '🧪 [TEST] 🟡 [B2B REG]',
    'Тестове приєднання представника партнера',
    `👤 ${actor.displayName}`,
    `username: ${actor.username ? `@${actor.username}` : '—'}`,
    `tgUserId: ${actor.tgUserId}`,
    `Компанія: ${partner.name}`,
    `Код: ${partner.inviteCode || '—'}`,
    'Контакт: +380671110000'
  ].join('\n'));
};

const nextPublicId = async () => {
  try {
    return await publicIdService.nextB2bRequestId('CD');
  } catch {
    return `CD-TST-${Date.now().toString(36).toUpperCase()}`;
  }
};

const createB2BRequestScenario = async (ctx: PipelineContext, actor: TestScenarioActor) => {
  if (!ctx.bot) throw new Error('missing_bot');
  const companyId = resolveCompanyId(ctx);
  const partner = await ensureTestPartner(ctx);
  const publicId = await nextPublicId();
  const request = await prisma.b2bRequest.create({
    data: {
      companyId,
      botId: ctx.bot.id,
      requesterPartnerId: partner.id,
      publicId,
      title: 'BMW X5',
      description: 'Тестовий B2B запит (без публікації в канал)',
      budgetMax: 30000,
      yearMin: 2018,
      yearMax: 2022,
      status: 'COLLECTING_VARIANTS',
      type: 'BUY',
      payload: {
        test: true,
        testScenario: 'b2b_request',
        createdByAdminTgId: actor.tgUserId,
        request: {
          brand: 'BMW',
          model: 'X5',
          budgetMax: 30000,
          yearMin: 2018,
          yearMax: 2022,
          fuel: 'Дизель',
          contact: '+380671112255',
          companyName: partner.name
        }
      } as any
    }
  });

  await sendAdmin(ctx, [
    '🧪 [TEST] 🔵 [B2B REQUEST]',
    `Запит: #${request.publicId || request.id}`,
    `Компанія: ${partner.name}`,
    `👤 ${actor.displayName}`,
    `username: ${actor.username ? `@${actor.username}` : '—'}`,
    `tgUserId: ${actor.tgUserId}`,
    'Контакт: +380671112255'
  ].join('\n'));
};

const createInventoryCar = async (ctx: PipelineContext, partnerId: string, status: string) => {
  const id = `tstcar_${Date.now()}_${randomSuffix()}`;
  return prisma.carListing.create({
    data: {
      id,
      source: 'MANUAL',
      status,
      companyId: resolveCompanyId(ctx),
      partnerCompanyId: partnerId,
      title: 'Skoda Kodiaq',
      price: 25900,
      currency: 'USD',
      year: 2019,
      mileage: 98000,
      location: 'Львів',
      thumbnail: null,
      mediaUrls: [],
      specs: {
        test: true,
        testScenario: status === 'HIDDEN' ? 'b2b_sell_form' : 'b2b_sell_inv',
        fuel: 'Дизель',
        transmission: 'Автомат',
        drive: 'Повний',
        condition: 'Добрий',
        contact: '+380671112266'
      } as any,
      description: 'Тестове авто для B2B'
    }
  });
};

const createB2BSellFormScenario = async (ctx: PipelineContext, actor: TestScenarioActor) => {
  const partner = await ensureTestPartner(ctx);
  const car = await createInventoryCar(ctx, partner.id, 'HIDDEN');
  await sendAdmin(ctx, [
    '🧪 [TEST] 🟣 [B2B SELL]',
    'Сценарій: продаж по формі',
    `Компанія: ${partner.name}`,
    `👤 ${actor.displayName}`,
    `tgUserId: ${actor.tgUserId}`,
    `Авто: ${car.title} ${car.year}`,
    `Ціна: ${car.price} USD`,
    'Контакт: +380671112266',
    `Car ID: ${car.id}`
  ].join('\n'));
};

const createB2BSellInventoryScenario = async (ctx: PipelineContext, actor: TestScenarioActor) => {
  const partner = await ensureTestPartner(ctx);
  let car = await prisma.carListing.findFirst({
    where: {
      companyId: resolveCompanyId(ctx),
      partnerCompanyId: partner.id,
      status: { in: ['AVAILABLE', 'HIDDEN'] }
    },
    orderBy: { createdAt: 'desc' }
  });

  if (!car) {
    car = await createInventoryCar(ctx, partner.id, 'AVAILABLE');
  }

  await sendAdmin(ctx, [
    '🧪 [TEST] 🟣 [B2B SELL][INVENTORY]',
    `Компанія: ${partner.name}`,
    `👤 ${actor.displayName}`,
    `tgUserId: ${actor.tgUserId}`,
    `Авто: ${car.title} ${car.year}`,
    `Ціна: ${car.price} USD`,
    `Car ID: ${car.id}`
  ].join('\n'));
};

const createB2BFitScenario = async (ctx: PipelineContext, actor: TestScenarioActor) => {
  if (!ctx.bot) throw new Error('missing_bot');
  const companyId = resolveCompanyId(ctx);
  const partner = await ensureTestPartner(ctx);
  const publicId = await nextPublicId();
  const request = await prisma.b2bRequest.create({
    data: {
      companyId,
      botId: ctx.bot.id,
      requesterPartnerId: partner.id,
      publicId,
      title: 'Toyota RAV4',
      status: 'COLLECTING_VARIANTS',
      type: 'BUY',
      payload: {
        test: true,
        testScenario: 'b2b_fit',
        createdByAdminTgId: actor.tgUserId,
        request: {
          contact: '+380671112277',
          companyName: partner.name
        }
      } as any
    }
  });

  const variant = await prisma.requestVariant.create({
    data: {
      requestId: request.id,
      status: 'APPROVED',
      source: 'MANUAL',
      title: 'Toyota RAV4 2020',
      price: 27900,
      currency: 'USD',
      year: 2020,
      mileage: 94000,
      location: 'Львів',
      companyName: partner.name,
      contact: '+380671112288',
      requesterDecision: 'FIT',
      requesterDecisionAt: new Date(),
      fitQueueStatus: 'NEW',
      fitQueuedAt: new Date(),
      sellerPartnerId: partner.id,
      specs: {
        test: true,
        testScenario: 'b2b_fit'
      } as any
    }
  });

  await sendAdmin(ctx, [
    '🧪 [TEST] 🔥 [FIT]',
    `Запит: #${request.publicId || request.id}`,
    `Варіант: ${variant.title || '—'}`,
    `Ціна: ${variant.price ? `${variant.price} USD` : '—'}`,
    'Контакт покупця: +380671112277',
    'Контакт продавця: +380671112288',
    `Компанія: ${partner.name}`
  ].join('\n'));
};

export const buildTestPanel = (template: string): TestPanelDefinition => {
  const upper = toText(template).toUpperCase();
  return upper === 'B2B' ? B2B_PANEL : LEAD_PANEL;
};

export const resolveScenarioFromPanelState = (
  panel: unknown,
  idx: number,
  chatId: string
): { ok: true; code: TestScenarioCode } | { ok: false; reason: 'stale' } => {
  if (!panel || typeof panel !== 'object') return { ok: false, reason: 'stale' };
  const data = panel as Record<string, any>;
  if (toText(data.chatId) !== toText(chatId)) return { ok: false, reason: 'stale' };
  const items = Array.isArray(data.items) ? data.items.map((it) => toText(it)).filter(Boolean) : [];
  if (!Number.isFinite(idx) || idx < 0 || idx >= items.length) return { ok: false, reason: 'stale' };
  return { ok: true, code: items[idx] as TestScenarioCode };
};

export const runTestScenario = async (
  ctx: PipelineContext,
  scenarioCode: TestScenarioCode,
  actor: TestScenarioActor
) => {
  switch (scenarioCode) {
    case 'lead_buy':
      await createLeadBuyScenario(ctx, actor);
      return { ok: true as const };
    case 'lead_sell':
      await createLeadSellScenario(ctx, actor);
      return { ok: true as const };
    case 'support':
      await createSupportScenario(ctx, actor);
      return { ok: true as const };
    case 'b2b_reg_new':
      await createB2BRegNewScenario(ctx, actor);
      return { ok: true as const };
    case 'b2b_reg_agent':
      await createB2BRegAgentScenario(ctx, actor);
      return { ok: true as const };
    case 'b2b_request':
      await createB2BRequestScenario(ctx, actor);
      return { ok: true as const };
    case 'b2b_sell_form':
      await createB2BSellFormScenario(ctx, actor);
      return { ok: true as const };
    case 'b2b_sell_inv':
      await createB2BSellInventoryScenario(ctx, actor);
      return { ok: true as const };
    case 'b2b_fit':
      await createB2BFitScenario(ctx, actor);
      return { ok: true as const };
    default:
      return { ok: false as const, message: 'unsupported_scenario' };
  }
};
