
export type UserRole = 'ADMIN' | 'MANAGER' | 'VIEWER' | 'SUPER_ADMIN' | 'OPERATOR' | 'DEALER';

export interface User {
    id: string;
    name: string;
    email: string;
    role: UserRole;
    username?: string;
    avatar?: string;
    companyId?: string;
    telegramUserId?: string;
}

export type Permission = 'MANAGE_USERS' | 'MANAGE_SETTINGS' | 'VIEW_ANALYTICS' | 'APPROVE_CONTENT' | 'SEND_CAMPAIGNS' | 'MANAGE_LEADS' | 'MANAGE_REQUESTS' | 'VIEW_LOGS' | 'MANAGE_COMPANIES' | 'MANAGE_ENTITIES';

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
    'ADMIN': ['MANAGE_USERS', 'MANAGE_SETTINGS', 'VIEW_ANALYTICS', 'APPROVE_CONTENT', 'SEND_CAMPAIGNS', 'MANAGE_LEADS', 'MANAGE_REQUESTS', 'VIEW_LOGS', 'MANAGE_COMPANIES', 'MANAGE_ENTITIES'],
    'SUPER_ADMIN': ['MANAGE_USERS', 'MANAGE_SETTINGS', 'VIEW_ANALYTICS', 'APPROVE_CONTENT', 'SEND_CAMPAIGNS', 'MANAGE_LEADS', 'MANAGE_REQUESTS', 'VIEW_LOGS', 'MANAGE_COMPANIES', 'MANAGE_ENTITIES'],
    'OWNER': ['MANAGE_USERS', 'MANAGE_SETTINGS', 'VIEW_ANALYTICS', 'APPROVE_CONTENT', 'SEND_CAMPAIGNS', 'MANAGE_LEADS', 'MANAGE_REQUESTS', 'VIEW_LOGS', 'MANAGE_COMPANIES', 'MANAGE_ENTITIES'],
    'MANAGER': ['VIEW_ANALYTICS', 'APPROVE_CONTENT', 'SEND_CAMPAIGNS', 'MANAGE_LEADS', 'MANAGE_REQUESTS'],
    'VIEWER': ['VIEW_ANALYTICS'],
    'OPERATOR': ['MANAGE_LEADS', 'MANAGE_REQUESTS'] // Legacy
};
